FROM nvcr.io/nvidia/pytorch:25.04-py3

ENV NVIDIA_DRIVER_CAPABILITIES=graphics,utility,compute

ARG LEROBOT_DATA_FOLDER
ARG HF_TOKEN

RUN apt-get update && \
    apt install -y tzdata && \
    ln -fs /usr/share/zoneinfo/America/Los_Angeles /etc/localtime && \
    apt install -y dnsutils && \
    apt-get update && \
    apt-get install -y \
    build-essential yasm cmake libtool git pkg-config \
    libass-dev libfreetype6-dev libvorbis-dev \
    autoconf automake texinfo tmux ffmpeg \
    curl vim sudo zip unzip wget htop man ca-certificates

RUN pip install --upgrade pip setuptools
RUN pip install uv
RUN sed -i s/dill==0.3.9/dill==0.3.8/g /etc/pip/constraint.txt
RUN sed -i s/scipy==1.15.2/scipy==1.15.3/g /etc/pip/constraint.txt
RUN pip install imageio h5py boto3 transformers[torch] deepspeed timm peft diffusers wandb tianshou dm_tree openai albumentations==1.4.18 decord==0.6.0 torchcodec==0.4.0
RUN mkdir -p /opt
RUN cd /opt && git clone https://github.com/facebookresearch/pytorch3d.git
RUN cd /opt/pytorch3d && pip install .

WORKDIR /workspace
COPY submodules/Isaac-GR00T/pyproject.toml /workspace/pyproject.toml
COPY submodules/Isaac-GR00T/gr00t /workspace/gr00t
COPY submodules/Isaac-GR00T/scripts /workspace/scripts
COPY submodules/Isaac-GR00T/demo_data /workspace/demo_data
COPY isaaclab_arena_gr00t/embodiments/gr1/gr1_arms_only_data_config.py /workspace/gr1_manip/gr1_arms_only_data_config.py
COPY isaaclab_arena_gr00t/embodiments/g1/g1_sim_wbc_data_config.py /workspace/g1_locomanip/g1_sim_wbc_data_config.py

RUN cd /workspace/ && uv sync && uv pip install -e .

RUN mkdir -p /workspace/pretrained_ckpts
RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
RUN sudo apt-get install git-lfs
RUN git-lfs install

RUN pip install huggingface-hub[cli]

# Create alias for hf command to use the system-installed version
RUN /usr/local/bin/hf download nvidia/GR00T-N1.6-3B --local-dir /workspace/pretrained_ckpts/GR00T-N1.6-3B --token ${HF_TOKEN}
RUN echo "alias hf='/usr/local/bin/hf'" >> /etc/bash.bashrc

# Add filebrowser to access intermediate checkpoints during OSMO training
# RUN curl -fsSL https://raw.githubusercontent.com/filebrowser/get/master/get.sh | bash
RUN curl -LO https://github.com/filebrowser/filebrowser/releases/download/v2.32.0/linux-amd64-filebrowser.tar.gz
RUN tar -xzvf linux-amd64-filebrowser.tar.gz
RUN mv filebrowser /usr/bin/
